name: glpi_tech_scanner
description: Application de consultation du parc IT via GLPI
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6

  # Scanner QR Code
  mobile_scanner: ^4.0.1

  # HTTP pour API GLPI
  http: ^1.2.0

  # Gestion d'état
  provider: ^6.1.1

  # Stockage local
  shared_preferences: ^2.2.2

  # Icônes
  flutter_launcher_icons: ^0.13.1

  # Firebase
  firebase_core: ^2.17.0
  cloud_firestore: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
